version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'sh -c "flask db upgrade && python main.py"'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    environment:
      FLASK_APP: main.py

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    volumes:
      - .:/app

  # db:
  #   image: mysql:5.7.22
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: admin
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - .dbdata:/var/lib/mysql
  #   ports:
  #     - 33066:3306
